---
- name: install rust by rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: role rust | manage pacman packages
  include_role: name=meta_pacman
  vars:
    pacman_packages: "{{ rust_pacman_packages }}"

- name: Ensure {{ cargo_packages | map(attribute='name') }} cargo packages are managed
  shell: cargo install  {{ item.name }};
  with_items: "{{ cargo_packages }}"
  changed_when:
    - "'is already installed' not in cargo_install_log.stdout"
    - "'is already installed' not in cargo_install_log.stderr"
  register: cargo_install_log
  when: item.state == "present"

- name: Ensure {{ cargo_packages | map(attribute='name') }} cargo packages are managed
  shell: cargo uninstall {{ item.name }}
  with_items: "{{ cargo_packages }}"
  register: cargo_uninstall_log
  when: item.state == "absent"
