---
- name: Ensure rust is installed
  include_tasks: install_rust.yml

- name: Ensure cargo packages {{  cargo_packages | map(attribute='name') }} are managed
  include_tasks: manage_package.yml

  loop: "{{ cargo_packages }}"
  loop_control:
    loop_var: item

