---
- hosts: localhost
  tasks:
    - include_vars: dir=vars
      tags: always

    - import_role: name=meta_pacman
      tags: [pacman, cli]

    - import_role: name=rust
      tags: [rust, cli]

    - import_role: name=aur
      tags: [aur]

    - import_role: name=zsh
      tags: [zsh, cli]

    - import_role: name=tmux
      tags: [tmux, cli]

    - import_role: name=ripgrep
      tags: [ripgrep, cli]

    - import_role: name=python
      tags: [python, cli]

    - import_role: name=yarn
      tags: [yarn, cli]

    - import_role: name=nvim
      tags: [nvim, cli]

    - import_role: name=docker
      tags: [docker, cli]

    - import_role: name=gui_apps
      tags: [gui]
    
    - import_role: name=i3
      tags: [i3, gui]

    - import_role: name=alacritty
      tags: [alacritty, gui]

    - import_role: name=font_iosevka
      tags: [fonts, gui]

    - import_role: name=1password
      tags: [1password, gui]
    
    - import_role: name=pritunl
      tags: [pritunl, gui]
