---
- hosts: all
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.cargo/bin"

  tasks:
    - import_role: name=homebrew
      tags: [homebrew, cli]

    - import_role: name=mas
      tags: [mas, gui]

    - import_role: name=meta_pacman
      tags: [pacman, cli]

    - import_role: name=rust
      tags: [rust, cli]

    - import_role: name=aur
      tags: [aur, cli]

    - import_role: name=zsh
      tags: [zsh, cli]

    - import_role: name=tmux
      tags: [tmux, cli]

    - import_role: name=dotfiles
      tags: [dotfiles, cli]

    - import_role: name=python
      tags: [python, cli]
      when: ansible_facts["os_family"] == "Archlinux"

    - import_role: name=yarn
      tags: [yarn, cli]

    - import_role: name=nvim
      tags: [nvim, cli]

    - import_role: name=docker
      tags: [docker, cli]
      when: ansible_facts["os_family"] == "Archlinux"

    - import_role: name=gui_apps
      tags: [gui]
      when: ansible_facts["os_family"] == "Archlinux"

    - import_role: name=1password
      tags: [1password, gui]
      when: ansible_facts["os_family"] == "Archlinux"

    - import_role: name=cron
      tags: [cron]

    # - import_role: name=wallpapers
    #   tags: [wallpapers, gui]
