#!/bin/bash

export DOTFILES=$HOME/.dotfileis

ln -s $DOTFILES/.zshrc       $HOME/.zshrc
ln -s $DOTFILES/.vimrc       $HOME/.vimrc
ln -s $DOTFILES/.jshintrc    $HOME/.jshintrc
ln -s $DOTFILES/.gitignore   $HOME/.gitignore
ln -s $DOTFILES/.search      $HOME/.search
ln -s $DOTFILES/.emotions    $HOME/.emotions
ln -s $DOTFILES/.gitconfig   $HOME/.gitconfig
