---
# TODO: instead of link t /usr/local/bin symlink bin to PATH
- name: role wallpapers | ensure pacman packages are managed
  include_role: name=meta_pacman
  vars:
    pacman_packages: "{{ wallpapers_pacman_packages }}"

- name: ensure wallpapers directory exists
  file:
    path: "{{ wallpapers_dir }}"
    state: directory

- name: ensure wallpapers are downloaded
  shell:
    cmd: "{{ wallpapers_download_command }}"
  register: wallpapers_output
  changed_when: "'Downloading' in wallpapers_output.stdout"

- name: ensure cron job to fetch new wallpapers is created
  cron:
    name: fetch wallpapers
    job: "{{ wallpapers_download_command }}"
    minute: 0
    state: present
