---
- name: Ensure {{ item.dest | dirname }} directory exists
  file:
    path: "{{ item.dest | dirname }}"
    state: directory

- name: Ensure {{ item.dest }} is linked
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: True
