---
- name: Ensure {{ gpg_keys | map(attribute=id) }} gpg keys are added
  community.general.pacman_key: "{{item}}"
  with_items: "{{ gpg_keys }}"
  become: true
  when:
    - ansible_facts["os_family"] == "Archlinux"
