---
- name: ensure pacman gui packages are managed
  include_role: name=meta_pacman
  vars:
    pacman_packages: "{{ pacman_gui_packages }}"

- name: ensure MAS gui packages are managed
  include_role: name=mas
  vars:
    pacman_packages: "{{ mas_gui_packages }}"

- name: ensure pacman gui packages are managed
  include_role: name=aur
  vars:
    aur_packages: "{{ aur_gui_packages }}"

- name: ensure cargo gui packages are managed
  include_role: name=rust
  vars:
    cargo_packages: "{{ cargo_gui_packages }}"
