[ -f ~/.exports ] && source ~/.exports

XDG_CONFIG_HOME=${HOME}/.config
ZSH_CONFIG_HOME=$XDG_CONFIG_HOME/zsh
ZSH_THEME="norm"
ZSH="${HOME}/.oh-my-zsh"

autoload -Uz compinit
compinit

for f (~/.config/zsh/config.d/*(N.))  . $f
source $HOME/.oh-my-zsh/oh-my-zsh.sh

# if [ "$TMUX" = "" ]; then tmux; fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
