XDG_CONFIG_HOME=${HOME}/.config
ZSH_CONFIG_HOME=$XDG_CONFIG_HOME/zsh
ZSH_THEME="norm"
ZSH="${HOME}/.oh-my-zsh"

for f (~/.config/zsh/config.d/*(N.))  . $f

autoload -U compinit && compinit

source $HOME/.oh-my-zsh/oh-my-zsh.sh

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
