windowrule = match:initial_class float, float on
windowrule = match:initial_class float_term, float on
windowrule = match:fullscreen_state_client 1, border_color rgb(7F848D) rgb(d8dee8)
windowrule = match:xwayland true, border_color rgb(f2f20d)

windowrule {
  name = launcher
  match:class = wofi

  border_size = 0
  stay_focused = on
}

windowrule {
  name = kitty_tail
  match:class = kitty
  opacity = 0.75
}

windowrule {
  name = kitty_oled_fullscreen
  match:fullscreen_state_client = 2
  opacity = override 1
}

windowrule {
  name = 1password
  match:class = 1password

  float = on
  size = 784 400
  move = (monitor_w-802) (monitor_h-444)
}


windowrule = match:title Picture in picture, tag +PiP
windowrule = match:title Picture-in-Picture, tag +PiP

windowrule {
  # Base window is 1920x1080, via 16:9 ratio
  # The base window is scaled down (by product it to 0.15, etc)
  # Then it positioned to the bottom right screen edge, via monitor_w-win_w and monitor_h-win_h
  # And then paddings are deducted from the position

  name = picture_in_picture
  match:tag = PiP

  float = on
  size = (1920*0.15) (1080*0.15)
  move = (monitor_w-(1920*0.15)-30) (monitor_h-(1080*0.15)-30)
  pin = on
  border_size = 0
}

windowrule {
  name = adw_bluetooth
  match:class = com.ezratweaver.AdwBluetooth

  float = on
  size = (monitor_w*0.6) (monitor_h*0.6)
  center = on
}

# # Dela
# windowrulev2 = float, class:^(dela)$
# windowrulev2 = size 80% 80%, title:^(dela)$
# windowrulev2 = center, class:^(dela)$


# TODO: Check if it's still used?
# windowrulev2 = float, class:^(yad)$
# windowrulev2 = center 1, floating:1, class:^(yad)$
# windowrulev2 = size 50% 50%, class:^(yad)$
# windowrulev2 = float, class:(zenity)
# windowrulev2 = center(1), class:(zenity)

windowrule = match:class imv, tag +preview
windowrule = match:class org.gnome.Loupe, tag +preview

windowrule {
  name = imv
  match:tag = preview
  float = on
  center = on
  size = (monitor_w*0.6) (monitor_h*0.6)
}



windowrule = tag +floating, match:title Volume Control
windowrule = tag +floating, match:title Network Connections
windowrule = tag +floating, match:class nm-connection-editor
windowrule = tag +floating, match:title File Operation Progress
windowrule = tag +floating, match:title Torrent Options
windowrule = tag +floating, match:title Media viewer
windowrule = tag +floating, match:class blueman-manager
windowrule = tag +floating, match:title Save File, match:class vivaldi-stable
windowrule = tag +floating, match:title Steam Settings, match:class steam
windowrule = tag +floating, match:title ^(Vivaldi Settings.*)$, match:class vivaldi-stable
windowrule = tag +floating, match:class vlc
windowrule = tag +floating, match:class nwg-look
windowrule = tag +floating, match:title ^(Opening.*)$, match:class firefox
windowrule = tag +floating, match:class mpv

windowrule = tag +floating, match:title Confirm to replace files, match:class thunar
windowrule = tag +floating, match:title ^(.* - Properties)$, match:class thunar
windowrule = float on, match:class thunar, match:title ^(Rename).*


# windowrulev2 = float, class:^(org\.freedesktop\.impl\.portal\.desktop\.kde)$
# windowrulev2 = fullscreen, title:^(imv-overlay)$
# # windowrulev2 = animation fade title:^(imv-overlay)$
# windowrulev2 = animation windowsIn 0, title:^(imv-overlay)$
# windowrulev2 = animation windowsOut 0, title:^(imv-overlay)$

# windowrulev2 = move 100% 100%, class:^(ueberzugpp_)
# windowrulev2 = noanim, class:^(ueberzugpp_)
# windowrulev2 = noborder, class:^(ueberzugpp_)


# blurls = swaync
# layerrule = blur, swaync
# layerrule = blur, top

# Floating Dialogs
