---
- name: role zsh | manage pacman packages
  include_role: name=meta_pacman
  vars:
    pacman_packages: "{{ zsh_pacman_packages }}"

- name: register zsh path
  shell: which zsh
  register: which_zsh
  changed_when: false

- name: ensure zsh is a current user shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ which_zsh.stdout }}"
  become: true

- name: ensure oh-my-zsh repo is checked out
  git:
    repo: "{{ zsh_ohmyzsh_repo }}"
    dest: "{{ zsh_ohmyzsh_dir }}"

- name: ensure oh_my_zsh plugins are checked out
  git: 
    repo: "{{ item.repo }}"
    dest: "{{ zsh_ohmyzsh_plugins_dir }}/{{ item.name }}"
  with_items: "{{ zsh_ohmyzsh_plugins }}"
  when: item.repo is defined
