---
dotfiles_source_dir: "{{ playbook_dir }}/files/configs/"
dotfiles_default_dest: "{{ lookup('env', 'HOME') }}/.configs"
dotfiles_dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default('configs_default_dest', True) }}"
