# windowrule = opacity 0.0 override 0.0 override, match:class:xwaylandvideobridge
# windowrule = noanim, match:class xwaylandvideobridge
# windowrule = nofocus, match:class xwaylandvideobridge
# windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
