directory: ~/Music
library: ~/Music/.beets-library.db
statefile: ~/Music/.beets-state.pickle

threaded: yes
asciify_path: yes

import:
  move: yes
  copy: no
  write: yes
  autotag: no
  incremental: yes

plugins: edit info smartplaylist types random mpdupdate play mpdstats convert fetchart embedart

paths:
  "folder::.+": $folder/$artist - $album - $track - $title
  default: inbox/$genre/$artist - $album - $track - $title

smartplaylist:
  playlist_dir: ~/Music/playlists
  relative_to: ~/Music
  playlists:
    - name: inbox.m3u
      query: '^folder::.+'

mpd:
  host: localhost
  port: 6600

art_filename: $albumartist - $album

fetchart:
  auto: yes
  sources:
    - coverart
    - itunes
    - amazon
  store_source: no

embedart:
  auto: yes
  ifempty: yes

convert:
  dest: ~/Dropbox/mp3/collection
  format: mp3
  never_convert_lossy_files: yes
  formats:
    mp3:
      command: ffmpeg -i $source -ab 320k -map_metadata 0 -id3v2_version 3 $dest
      extension: mp3
