---
- name: role tmux | manage pacman packages
  include_role:
    name: meta_pacman
  vars:
    pacman_packages: "{{ tmux_pacman_packages }}"

- name: ensure tpm is installed
  git:
    repo: "{{ tmux_tpm_repo }}"
    dest: "{{ tmux_config_dir }}/plugins/tpm"
    accept_hostkey: yes 
