---
- name: role yarn | manage pacman packages
  include_role:
    name: meta_pacman
  vars:
    pacman_packages: "{{ yarn_pacman_packages }}"

- name: set fact about yarn and node are managed
  set_fact:
    yarn_is_managed: true

