---
- name: role docker | manage pacman packages
  include_role: name=meta_pacman
  vars:
    pacman_packages: "{{ docker_pacman_packages }}"

- name: ensure user is in the docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: True
  become: True

- name: ensure docker.service is enabled
  include_role: name=systemd
  vars:
    systemd_services: "{{ docker_systemd_services }}"
  when:
    - "'microsoft' not in ansible_kernel"

