decorations: false
background_opacity: 0.75

window:
  padding:
    x: 2
    y: 12

colors:
  # Default colors
  primary:
    background: '0x2e3340'
    foreground: '0xd8dee8'

  # Cursor colors
  cursor:
    text:   '0x3b4251'
    cursor: '0xd8dee8'

  # Normal colors
  normal:
    black:   '0x3b4251'
    red:     '0xbf6069'
    green:   '0xa3be8b'
    yellow:  '0xeacb8a'
    blue:    '0x81a1c1'
    magenta: '0xb48dac'
    cyan:    '0x88c0d0'
    white:   '0xe5e9f0'

  # Bright colors
  bright:
    black:   '0x616e86'
    red:     '0xbf6069'
    green:   '0xa3be8b'
    yellow:  '0xeacb8a'
    blue:    '0x81a1c1'
    magenta: '0xb48dac'
    cyan:    '0x8fbcbb'
    white:   '0xeceef4'

font:
  normal:
    family: iosevka
  size: 15.0
