name: Test

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: shuva1ov/archlinux-ansible
    steps:
      - uses: actions/checkout@v1
      - name: Run playbook
        run: ansible-playbook dotfiles.yml

